
package com;

import java.util.Optional;

import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/expenses") // This means URL's start with /demo (after Application path)
public class ExpensesController {
  @Autowired // This means to get the bean called ExpensesRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ExpensesRepository ExpensesRepository;


  @GetMapping(path="/")
  public  @ResponseBody Iterable<Expenses> getAllExpensess() {
    // This returns a JSON or XML with the Expensess
    return ExpensesRepository.findAll();
  }
  

}