version: '3.1'

services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: family_finance
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"

  book-manager-app:
    restart: on-failure
    build: ./finance/
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql


  user:
    build: ./user/
    restart: always
    ports:
      - 8182:8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: springboot-mongo
    ports:  # for demo/debug purpose only
      - 27018:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always
