version: '3.1'

services:
  docker-mysql:
    restart: always
    container_name: docker-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: family_finance
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"


  docker-mysql-expense:
    restart: always
    container_name: docker-mysql-expense
    image: mysql
    environment:
      MYSQL_DATABASE: expense
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6036:3306"


  expense:
    build: ./expense/
    restart: always
    expose:
      - "8183"
    ports:
      - 8183:8183
    depends_on:
      - docker-mysql-expense


  docker-mysql-user:
    restart: always
    container_name: docker-mysql-user
    image: mysql
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6034:3306"

  shared-finance:
    build: ./sharedFinance/
    restart: always
    expose:
      - "8185"
    ports:
      - 8185:8185
    depends_on:
      - docker-mysql-shared-finance


  docker-mysql-shared-finance:
    restart: always
    container_name: docker-mysql-shared-finance
    image: mysql
    environment:
      MYSQL_DATABASE: sharedFinance
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6038:3306"


  income:
    build: ./income/
    restart: always
    expose:
      - "8184"
    ports:
      - 8184:8184
    depends_on:
      - docker-mysql-income


  docker-mysql-income:
    restart: always
    container_name: docker-mysql-income
    image: mysql
    environment:
      MYSQL_DATABASE: income
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6037:3306"


  finance:
    restart: on-failure
    build: ./finance/
    expose:
      - "10222"
    ports:
      - 10222:10222
    environment:
      USER_SERVICE_URL: http://user:8182
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql


  user:
    build: ./user/
    restart: always
    expose:
      - "8182"
    ports:
      - 8182:8182
    depends_on:
      - docker-mysql-user



  docker-mysql-category:
    restart: always
    container_name: docker-mysql-category
    image: mysql
    environment:
      MYSQL_DATABASE: category
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "6035:3306"


  category:
    restart: on-failure
    build: ./category/
    expose:
      - "8186"
    ports:
      - 8186:8186
    environment:
      USER_SERVICE_URL: http://user:8182
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql-category
