FROM openjdk:11-jre-slim

MAINTAINER Maicon Moretto <maiconmorettos@gmail.com>

WORKDIR /app

COPY /target/familyfinance-user-0.0.1-SNAPSHOT.jar /app

CMD java -jar familyfinance-user-0.0.1-SNAPSHOT.jar

